(()=>{
const KEY='latino-built-field-estimator-v3',OLD='latino-built-field-estimator-v2';let timer;
const legacyNames={"attic": ["Attic Insulation", "Aislamiento de \u00c1tico"], "wall": ["Wall Insulation", "Aislamiento de Paredes"], "floor": ["Floor Insulation", "Aislamiento de Piso"], "windows": ["Windows (Single-Pane Replacement)", "Ventanas (Reemplazo de Un Panel)"], "ductlessHP": ["Ductless Heat Pump", "Bomba de Calor sin Ductos"], "ductedHP": ["Ducted Heat Pump", "Bomba de Calor con Ductos"], "extCapHP": ["Extended Capacity Heat Pump", "Bomba de Calor de Capacidad Extendida"], "gasFurnace": ["Gas Furnace (95%+ AFUE)", "Calefactor de Gas (95%+ AFUE)"], "smartThermo": ["Smart Thermostat", "Termostato Inteligente"], "tanklessWH": ["Gas Tankless Water Heater", "Calentador de Agua a Gas sin Tanque"], "gasFireplace": ["Gas Fireplace (FE 75%+)", "Chimenea de Gas (FE 75%+)"]};
function fields(){return [...document.querySelectorAll('input[id],select[id],textarea[id]')].filter(el=>!el.id.startsWith('work-'))}
function save(){try{const data={__work:state.work,__invoice:lineItems,__estimateId:state.id,__lang:lang};fields().forEach(el=>data[el.id]={value:el.value,checked:!!el.checked,type:el.type});localStorage.setItem(KEY,JSON.stringify(data));document.getElementById('lb-save-state').textContent=t('Saved on this device','Guardado en este dispositivo')}catch(e){document.getElementById('lb-save-state').textContent=t('Unable to save on this device','No se pudo guardar en este dispositivo')}}
const actions=document.querySelector('.topbar-actions');const status=document.createElement('span');status.id='lb-save-state';status.className='lb-save';status.textContent='Saved on this device';actions?.prepend(status);
try{const data=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem(OLD)||'null');if(data){
if(data.__lang==='es')lang='es';
if(Array.isArray(data.__work)){state.work=data.__work.filter(w=>w&&Number.isInteger(w.id)).map(w=>({...w,desc:String(w.desc||''),qty:Math.max(0,Number(w.qty)||0),price:Math.max(0,Number(w.price)||0)}));workCounter=Math.max(0,...state.work.map(w=>w.id));}
else{const rows=[];Object.entries(legacyNames).forEach(([id,names])=>{if(data['chk-'+id]?.checked)rows.push({id:rows.length+1,desc:names[lang==='es'?1:0],cat:'labor',qty:1,price:Math.max(0,Number(data['labor-'+id]?.value)||0)})});if(rows.length){state.work=rows;workCounter=rows.length}}
if(typeof data.__estimateId==='string'){state.id=data.__estimateId;document.getElementById('estimateId').textContent=state.id}
if(Array.isArray(data.__invoice)){document.getElementById('lineBody').replaceChildren();lineItems=[];lineCounter=0;data.__invoice.forEach(item=>{if(!Number.isInteger(item.id))return;lineItems.push({...item,desc:String(item.desc||'')});lineCounter=Math.max(lineCounter,item.id);renderLine(item.id,item.desc||'',item.cat,item.qty,item.price)})}
Object.entries(data).forEach(([id,v])=>{if(id.startsWith('__'))return;const el=document.getElementById(id);if(el)el.value=v.value??''});applyLang();update();calcInvoice();
}}catch(e){status.textContent='Saved draft could not be restored'}
function branding(){document.getElementById('tb-title').textContent=t('Field Estimator','Estimador de Trabajo');document.getElementById('tb-sub').textContent='Latino Built · Pro Source';const icon=document.querySelector('.topbar-icon');if(icon){icon.textContent='LB';icon.setAttribute('aria-label','Latino Built')}document.getElementById('langBtn').textContent=lang==='es'?'English':'Español';document.querySelectorAll('.fg').forEach(group=>{const label=group.querySelector('label'),input=group.querySelector('input,select,textarea');if(label&&input?.id)label.setAttribute('for',input.id)})}branding();document.getElementById('langBtn').addEventListener('click',branding);
document.querySelectorAll('.nav-tab').forEach(el=>{el.setAttribute('role','button');el.tabIndex=0;el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}})});
const queue=()=>{clearTimeout(timer);timer=setTimeout(save,250)};['input','change','click'].forEach(ev=>document.addEventListener(ev,queue,true));window.addEventListener('beforeunload',save);
})();
